### ISSUE TITLE
Znote using PHP 7

### ISSUE THREAD

**Issue by gregorecruzeiro** [Znote/ZnoteAAC#352] opened 2019-03-21 02:33 UTC
Is not it time to update the website for php 7x? Since most of the servers use this version because it is newer?

The array for example has changed the way it is treated according to the manual below.

http://php.net/manual/en/language.types.array.php

This is just an issue to be discussed.

**Comment by Znote** [comment] 2019-03-21 08:29
Where does the arrays not work as intended? 

I'm currently using Znote AAC with PHP 7.2 without seeing any obvious problems. 
If you catch warning or error notices, post them so I can see them and fix them. 👍 

I would prefer Znote AAC to be backward compatible at least back to 5.6, but I don't see much point in supporting 5.3 any more.

**Comment by gregorecruzeiro** [comment] 2019-03-21 12:31
417/5000
I am not on my computer at the moment, but I remember there is an error in the /special/repairSkills.php file.

I had saved the error, go below.

Warning: require_once (engine / init.php): failed to open stream: No such file or directory in special \ repairSkills.php on line 1

Fatal error: require_once (): Failed opening required 'engine / init.php' (include_path = 'C: \ xampp \ php \ PEAR') in special \ repairSkills.php on line 1

**Comment by Znote** [comment] 2019-03-22 18:31
repairSkills.php has to be moved outside of the special folder into the root folder, and then you need to access it. It only works for TFS 0.3 though, and should only be used if you actually need to fix skills. (like if you deleted player_skills table and need to re-add the rows).

**Comment by Znote** [comment] 2019-04-01 07:40
Is there any other issues you have found in Znote AAC due to PHP 7?

**Comment by glombers** [comment] 2019-04-01 18:49
@gregorecruzeiro With me on the site on xampp showed a lot of errors but as I put the site on nginx these errors have disappeared. It simply shows how to improve something but in practice it works

**Comment by gregorecruzeiro** [comment] 2019-04-15 01:19
can close

**Comment by Znote** [comment] 2019-04-20 13:55
I'll give it a test run in xampp with latest php version first before closing this issue. Just to clean up warning messages should I find any.

**Comment by divinity76** [comment] 2019-04-24 20:57
as for minimum version, my vote goes to officially setting the minimum php version to 5.6 for now. (honestly does anyone want to look into issues that can only be reproduced on php <= 5.5? i don't think so)

**Comment by Znote** [comment] 2019-11-11 05:59
Tested Znote AAC in PHP 7.4, no issues. 
Bumped required PHP version to 5.6, so we can begin to use [] array declarations.

**Closed by Znote** 2019-11-11 05:59 UTC
Labels: question
